import Link from "next/link";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import { SiteFooter, SiteHeader } from "@/components/site-shell";

export const metadata = { title: "Easylink eSIM | EasyDesignTech", description: "Travel connectivity from the EasyDesignTech family." };

export default function EasylinkPage() {
  return <div className="site-shell"><SiteHeader /><main className="detail-main esim-detail"><section className="venture-detail-hero esim-detail-hero"><div className="container venture-detail-layout"><div className="venture-detail-copy"><p className="eyebrow"><span className="eyebrow-line" /> EASYDESIGNTECH / CONNECTIVITY</p><h1>Go further.<br /><em>Stay connected.</em></h1><p>Easylink eSIM is built for travellers, remote workers and people on the move who want straightforward mobile data without the usual friction.</p><div className="detail-actions"><a className="button button-light" href="https://www.geteasylink.app/" target="_blank" rel="noopener noreferrer">Visit Easylink eSIM <ArrowUpRight size={18} aria-hidden="true" /></a><Link className="detail-inline-link" href="#vision">Explore the vision <ArrowRight size={18} aria-hidden="true" /></Link></div></div><div className="esim-detail-art"><img src="/esim-globe.webp" alt="Concept visual of a connected globe" /><span>EASY TRAVEL.<br />EASY CONNECT.</span></div></div></section><section className="venture-statement" id="vision"><div className="container statement-grid"><p className="eyebrow dark-eyebrow"><span className="eyebrow-line" /> THE IDEA</p><div><h2>Connectivity<br />that travels.</h2><p>Explore local, regional and global data options, activate digitally and stay focused on the journey ahead. Easylink eSIM is part of a more connected travel experience across the EasyDesignTech family.</p><div className="statement-tags"><span>Choose</span><span>Activate</span><span>Connect</span></div><a className="statement-cta" href="https://www.geteasylink.app/" target="_blank" rel="noopener noreferrer">Explore Easylink eSIM <ArrowUpRight size={17} aria-hidden="true" /></a></div></div></section><section className="crosslink-section"><div className="container"><p>ANOTHER PART OF THE FAMILY</p><Link href="/easyholi">Plan the journey with EasyHoli <ArrowUpRight size={28} aria-hidden="true" /></Link></div></section></main><SiteFooter /></div>;
}
