import Link from "next/link";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import { SiteFooter, SiteHeader } from "@/components/site-shell";

export const metadata = { title: "EasyProperties | EasyDesignTech", description: "Explore the EasyProperties vision within the EasyDesignTech family." };

export default function EasyPropertiesPage() {
  return <div className="site-shell"><SiteHeader /><main className="detail-main property-detail"><section className="venture-detail-hero property-detail-hero"><div className="container venture-detail-layout"><div className="venture-detail-copy"><p className="eyebrow"><span className="eyebrow-line" /> EASYDESIGNTECH / PROPERTY</p><h1>Places worth<br /><em>finding.</em></h1><p>EasyProperties is shaping a simpler way to explore property, with clearer information and a more confident path from discovery to decision.</p><div className="detail-actions"><Link className="button button-dark" href="/contact?interest=EasyProperties">Enquire about EasyProperties <ArrowUpRight size={18} aria-hidden="true" /></Link><Link className="detail-inline-link" href="#vision">Explore the vision <ArrowRight size={18} aria-hidden="true" /></Link></div></div><div className="venture-detail-image"><img src="/property.webp" alt="Concept image showing a modern property interior" /><span>THE EASYPROPERTIES VISION</span></div></div></section><section className="venture-statement" id="vision"><div className="container statement-grid"><p className="eyebrow dark-eyebrow"><span className="eyebrow-line" /> THE IDEA</p><div><h2>Property, with<br />more clarity.</h2><p>Built around discovery, useful details and a smoother experience, EasyProperties aims to help people navigate property opportunities with less friction.</p><div className="statement-tags"><span>Discover</span><span>Understand</span><span>Decide</span></div><Link className="statement-cta" href="/contact?interest=EasyProperties">Ask us about EasyProperties <ArrowUpRight size={17} aria-hidden="true" /></Link></div></div></section><section className="crosslink-section"><div className="container"><p>ANOTHER PART OF THE FAMILY</p><Link href="/easyholi">Go somewhere new with EasyHoli <ArrowUpRight size={28} aria-hidden="true" /></Link></div></section></main><SiteFooter /></div>;
}
