import Link from "next/link";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import { SiteFooter, SiteHeader } from "@/components/site-shell";

export const metadata = { title: "EasyHoli | EasyDesignTech", description: "Discover the EasyHoli travel vision within the EasyDesignTech family." };

export default function EasyHoliPage() {
  return <div className="site-shell"><SiteHeader /><main className="detail-main holi-detail"><section className="venture-detail-hero holi-detail-hero"><div className="container venture-detail-layout"><div className="venture-detail-copy"><p className="eyebrow"><span className="eyebrow-line" /> EASYDESIGNTECH / TRAVEL</p><h1>More journey.<br /><em>Less juggling.</em></h1><p>EasyHoli brings the pieces of a trip into one thoughtful experience, from inspiration and planning to the details that make every day easier.</p><div className="detail-actions"><Link className="button button-dark" href="/contact?interest=EasyHoli">Enquire about EasyHoli <ArrowUpRight size={18} aria-hidden="true" /></Link><Link className="detail-inline-link" href="#vision">Explore the vision <ArrowRight size={18} aria-hidden="true" /></Link></div></div><div className="venture-detail-image"><img src="/travel.webp" alt="Concept image showing a coastal travel destination" /><span>THE EASYHOLI VISION</span></div></div></section><section className="venture-statement" id="vision"><div className="container statement-grid"><p className="eyebrow dark-eyebrow"><span className="eyebrow-line" /> THE IDEA</p><div><h2>A better way<br />to get away.</h2><p>EasyHoli is being designed to bring flights, stays, activities, shared plans and travel expenses into a more connected journey. Easylink eSIM can help keep travellers connected along the way.</p><div className="statement-tags"><span>Plan</span><span>Explore</span><span>Connect</span></div><Link className="statement-cta" href="/contact?interest=EasyHoli">Ask us about EasyHoli <ArrowUpRight size={17} aria-hidden="true" /></Link></div></div></section><section className="crosslink-section"><div className="container"><p>ANOTHER PART OF THE FAMILY</p><a href="https://www.geteasylink.app/">Stay connected with Easylink eSIM <ArrowUpRight size={28} aria-hidden="true" /></a></div></section></main><SiteFooter /></div>;
}
